services:

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    networks:
      - aegis-net

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "8082:3000"
    networks:
      - aegis-net

  metasploitable:
    image: tleemcjr/metasploitable2
    ports:
      - "8083:80"
      - "2222:22"
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - aegis-net
    tty: true
    stdin_open: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - aegis-net

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8080
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.key=aegis_zap_key
    ports:
      - "8090:8080"
    networks:
      - aegis-net

networks:
  aegis-net:
    driver: bridge
