# Generated by Django 6.0.2 on 2026-02-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('scan_mode', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.TextField()),
                ('found_vulnerabilities', models.JSONField(default=dict)),
                ('is_critical', models.BooleanField(default=False)),
            ],
        ),
    ]
