# Generated by Django 4.2.11 on 2026-03-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ai_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='severity',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='RUNNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan_mode',
            field=models.CharField(choices=[('lab', 'Lab Audit'), ('web', 'Web Audit'), ('top100', 'Quick Recon'), ('full', 'Deep Penetration')], default='lab', max_length=50),
        ),
        migrations.CreateModel(
            name='ForensicEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PCAP', 'Packet Capture'), ('LOG', 'System Log'), ('SCREENSHOT', 'Screenshot'), ('FILE', 'Extracted File'), ('HASH', 'File Hash')], max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='scanner_ui.scanresult')),
            ],
        ),
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_used', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=255)),
                ('target_port', models.IntegerField(null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='scanner_ui.scanresult')),
            ],
        ),
    ]
